+incdir+./../FPU_ADD_SUB/lib/
./../../03_verif/FPU_ADD_SUB/tb_FPU_add_sub.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_EXP_adjust.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_EXP_comp.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_EXP_rounding.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_EXP_sub.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_EXP_swap.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_MAN_ALU.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_MAN_rounding.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_MAN_swap.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_NOR_unit.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_PSC_unit.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_SIGN_unit.sv
./../../02_rtl/FPU_ADD_SUB/FPU_add_sub.sv
./../../02_rtl/FPU_COMMON/CLA_4bit.sv
./../../02_rtl/FPU_COMMON/CLA_8bit.sv
./../../02_rtl/FPU_COMMON/CLA_24bit.sv
./../../02_rtl/FPU_COMMON/CLS_4bit.sv
./../../02_rtl/FPU_COMMON/COMP_4bit.sv
./../../02_rtl/FPU_COMMON/COMP_8bit.sv
./../../02_rtl/FPU_COMMON/COMP_24bit.sv
./../../02_rtl/FPU_COMMON/COMP_CLA_24bit.sv
./../../02_rtl/FPU_COMMON/LOPD_4bit.sv
./../../02_rtl/FPU_COMMON/LOPD_8bit.sv
./../../02_rtl/FPU_COMMON/LOPD_16bit.sv
./../../02_rtl/FPU_COMMON/LOPD_24bit.sv
./../../02_rtl/FPU_COMMON/SHF_left.sv
./../../02_rtl/FPU_COMMON/SHF_right.sv