+incdir+./../FPU_ADD_SUB/lib/
./../../03_verif/FPU_ADD_SUB/tb_FPU_add_sub.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_CLA_4bit.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_CLA_8bit.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_CLA_24bit.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_CLS_4bit.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_COMP_4bit.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_COMP_8bit.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_COMP_24bit.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_EXP_adjust.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_EXP_comp.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_EXP_rounding.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_EXP_sub.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_EXP_swap.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_LOPD_8bit.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_LOPD_16bit.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_LOPD_24bit.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_MAN_ALU.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_MAN_rounding.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_MAN_swap.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_NOR_unit.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_PSC_unit.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_SHF_left.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_SHF_right.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_SIGN_unit.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_SUB_4bit.sv
./../../02_rtl/FPU_ADD_SUB/ADD_SUB_SUB_8bit.sv
./../../02_rtl/FPU_ADD_SUB/FPU_add_sub.sv